//
//  beebemrcids.h
//  BeebEm5
//
//  Created by Commander Coder on 30/09/2022.
//  Copyright © 2022 Andrew Hague. All rights reserved.
//

#ifndef beebemrcids_h
#define beebemrcids_h

#include "beebemrc.h"
#include <map>

#define ID IDM_FULLSCREEN

std::map<int,int> ID2RC =
{
{'sfps', IDM_SPEEDANDFPS},
{'rund', IDM_RUNDISC},
{'opn0', IDM_LOADDISC0},
{'opn1', IDM_LOADDISC1},
{'new0', IDM_NEWDISC0},
{'new1', IDM_NEWDISC1},
{'rest', ID},
{'bbcb', ID_MODELB},
{'bbci', ID_MODELBINT},
{'bbcp', ID_MODELBPLUS},
{'bbcm', ID_MASTER128},
{'tube', ID},
{'t186', ID},
{'tz80', ID},
{'tarm', ID},
{'az80', ID},
{'sRT ', ID},
{'s50 ', IDM_50FPS},
{'s25 ', IDM_25FPS},
{'s10 ', IDM_10FPS},
{'s5  ', IDM_5FPS },
{'s1  ', IDM_1FPS },
{'f100', IDM_FIXEDSPEED100 },
{'f5  ', IDM_FIXEDSPEED5   },
{'f2  ', IDM_FIXEDSPEED2   },
{'f1.5', IDM_FIXEDSPEED1_5 },
{'f1.2', IDM_FIXEDSPEED1_25},
{'f1.1', IDM_FIXEDSPEED1_1 },
{'f0.9', IDM_FIXEDSPEED0_9 },
{'f0.7', IDM_FIXEDSPEED0_75},
{'f50 ', IDM_FIXEDSPEED50  },
{'f0.2', IDM_FIXEDSPEED0_25},
{'f10 ', IDM_FIXEDSPEED10  },
{'f0.5', IDM_FIXEDSPEED0_5 },
{'f0.1', IDM_FIXEDSPEED0_1 },
{'monr', ID},
{'monb', ID},
{'mong', ID},
{'mona', ID},
{'wrp0', IDM_WPDISC0},
{'wrp1', IDM_WPDISC1},
{'wpol', IDM_WPONLOAD},
{'siz1', ID},
{'siz2', ID},
{'siz3', ID},
{'siz4', ID},
{'siz5', ID},
{'siz6', ID},
{'siz7', ID},
{'siz8', ID},
{'siz9', ID},
{'siza', ID},
{'sizb', ID},
{'vfsc', ID},
{'vmar', ID},
{'volf', ID},
{'volh', ID},
{'volm', ID},
{'voll', ID},
{'sndc', ID},
{'sond', ID},
{'sped', ID},
{'enet', ID},
{'igil', ID},
{'hard', ID},
{'docu', ID},
{'extr', ID},
{'full', ID},
{'ifd0', ID},
{'ifd1', ID},
{'ifd2', ID},
{'ifd3', ID},
        {'efd0', ID},
{'efd1', ID},
{'efd2', ID},
{'efd3', ID},
{'roma', IDM_ALLOWWRITES_ROM0},
{'romb', IDM_ALLOWWRITES_ROM1},
{'romc', IDM_ALLOWWRITES_ROM2},
{'romd', IDM_ALLOWWRITES_ROM3},
{'rome', IDM_ALLOWWRITES_ROM4},
{'romf', IDM_ALLOWWRITES_ROM5},
{'romg', IDM_ALLOWWRITES_ROM6},
{'romh', IDM_ALLOWWRITES_ROM7},
{'romi', IDM_ALLOWWRITES_ROM8},
{'romj', IDM_ALLOWWRITES_ROM9},
{'romk', IDM_ALLOWWRITES_ROMA},
{'roml', IDM_ALLOWWRITES_ROMB},
{'romm', IDM_ALLOWWRITES_ROMC},
{'romn', IDM_ALLOWWRITES_ROMD},
{'romo', IDM_ALLOWWRITES_ROME},
{'romp', IDM_ALLOWWRITES_ROMF},
{'ledr', ID_RED_LEDS     },
{'ledg', ID_GREEN_LEDS   },
{'ledk', ID_SHOW_KBLEDS  },
{'ledd', ID_SHOW_DISCLEDS},
{'savp', IDM_SAVE_PREFS},
{'qukl', IDM_QUICKLOAD},
{'quks', IDM_QUICKSAVE},
{'rsts', IDM_LOADSTATE},
{'savs', IDM_SAVESTATE},
{'pfle', ID},
        {'pclp', ID},
{'prnt', ID},
{'kmas', ID},
        {'copy', ID},
        {'past', ID},
{'trac', ID},
{'amxo', ID},
{'amxl', ID},
{'amx1', ID},
{'amx3', ID},
{'amx6', ID},
{'axp5', ID},
{'axp3', ID},
{'axp1', ID},
{'axm1', ID},
{'axm3', ID},
{'axm5', ID},
        {'ofwm', ID},
        {'msea', ID},
{'msed', ID},
{'opnt', ID_LOADTAPE},
{'tpfa', ID},
{'tpmf', ID},
{'tpms', ID},
{'tpno', ID},
{'tpso', ID},
{'tpcr', ID},
{'ddso', ID},
{'tpre', ID},
{'tpul', ID},
        {'tpco', ID},
        {'dbgr', ID},
        {'upbo', ID},
        {'uprm', ID},
        {'abou', IDM_ABOUT},
        {'kusr', ID},
        {'lukm', ID},
        {'sukm', ID},
        {'udkm', ID},
        {'dkm ', ID},
{'vidc', ID},
{'vide', ID},
{'skp0', IDM_VIDEOSKIP0},
{'skp1', IDM_VIDEOSKIP1},
{'skp2', IDM_VIDEOSKIP2},
{'skp3', IDM_VIDEOSKIP3},
{'skp4', IDM_VIDEOSKIP4},
{'skp5', IDM_VIDEOSKIP5},
{'rec1', ID},
{'rec2', ID},
{'rec3', ID},
{'rec4', ID},
{'mbof', ID},
{'mb2f', ID},
{'mb4f', ID},
{'mb8f', ID},
{'ejd0', IDM_EJECTDISC0},
{'ejd1', IDM_EJECTDISC1},
{'snev', ID},
{'txte', ID},
{'txtd', ID},
{'txts', ID},
{'hdre', ID},
{'rs42', ID},
{'sdts', ID},
{'sdep', ID},
{'sdsp', ID},
{'page', ID},
{'prns', ID},
{'cpyc', ID},
{'invb', ID},
{'swtd', ID},
{'mbcn', ID},
{'mbca', ID},
{'mbco', ID},
{'mbcw', ID}
    
};

#endif /* beebemrcids_h */
